<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Company>ContestCharacters</Company>
        <Product>ContestCharacters</Product>
        <AssemblyName>ContestCharactersUnlockBuild</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>$(Net6)\0Harmony.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppCoherence">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppCoherence.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCoherence.Common">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppCoherence.Common.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCoherence.Core">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppCoherence.Core.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppCoherence.Toolkit">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppCoherence.Toolkit.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppDOTween">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppDOTween.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppDOTween.Modules">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppDOTween.Modules.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppInterop.Runtime">
        <HintPath>$(Net6)\Il2CppInterop.Runtime.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2Cppl2localization">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2Cppl2localization.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppMAScripts">
        <HintPath>$(Il2)\Il2CppMAScripts.dll</HintPath>
      </Reference>
      <Reference Include="Il2Cppmscorlib">
        <HintPath>$(Il2)\Il2Cppmscorlib.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppNewtonsoft.Json">
        <HintPath>$(Il2)\Il2CppNewtonsoft.Json.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppPauseSystem">
        <HintPath>$(Il2)\Il2CppPauseSystem.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppPhaserPort">
        <HintPath>$(Il2)\Il2CppPhaserPort.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppSystem">
        <HintPath>$(Il2)\Il2CppSystem.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppSystem.Core">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
      </Reference>
      <Reference Include="Il2CppVampireSurvivors.Runtime">
        <HintPath>$(Il2)\Il2CppVampireSurvivors.Runtime.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Il2CppZenject">
        <HintPath>$(Il2)\Il2CppZenject.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="MelonLoader">
        <HintPath>$(Net6)\MelonLoader.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Newtonsoft.Json">
        <HintPath>$(Net6)\Newtonsoft.Json.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="Unity.Mathematics">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Unity.Mathematics.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.2D.Runtime">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Universal.2D.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.RenderPipelines.Universal.Runtime">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.AudioModule">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.AudioModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>$(Il2)\UnityEngine.CoreModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.Il2CppAssetBundleManager">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\net6\UnityEngine.Il2CppAssetBundleManager.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.ParticleSystemModule">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.ParticleSystemModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TilemapModule">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.TilemapModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>..\..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\VSModded\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoffinTech\CoffinTech.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="resources\contestbundle" />
    </ItemGroup>

</Project>
